### ISSUE TITLE
Znuny4OTRSInput can't unset CustomerUser autocompletes

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-Repo#12]
Currently the following call has no effect:

``` JavaScript
Core.Form.Znuny4OTRSInput.Set('CustomerUserID');
```

This should be fixed

**Comment by dennykorsukewitz** [comment]
Hi @thorsteneckel,

is this bug still present?  I can't reproduce this bug in OTRS 5 and 6

**Comment by thorsteneckel** [comment]
Probably not if it can't be reproduced. Thanks for checking! Closing now.

**Comment by dennykorsukewitz** [comment]
👍🖖
