### ISSUE TITLE
Can't install beside KIX4OTRS

### ISSUE THREAD

**Issue by strikegun** [znuny/Znuny4OTRS-Repo#15]
Hi,
if I try to install the repo I get:
Can't install/upgrade package, file var/httpd/htdocs/js/Core.UI.InputFields.js already used in package KIX4OTRS-8.0.5!

Any bypass?

**Comment by thorsteneckel** [comment]
Hi @strikegun 

Please refer to this issue: https://github.com/znuny/Znuny4OTRS-Repo/issues/13

Greetings,
  Thorsten
