### ISSUE TITLE
regex only match first one

### ISSUE THREAD

**Issue by NeverMin** [znuny/Znuny4OTRS-Repo#18]
### Expected behavior
![image](https://user-images.githubusercontent.com/2797432/68298530-928cf700-00d4-11ea-8b67-3407e17aad59.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/2797432/68298393-34f8aa80-00d4-11ea-9f88-fd91619ce2ea.png)

### How to reproduce
1. default install otrs and Znuny4OTRS 6.0.50
1. open [system config](https://localhost/otrs/index.pl?Action=AdminSystemConfigurationGroup;RootNavigation=Frontend::Agent)

### Environment
 - OS: CentOS 7.4
 - Browser: any
 - OTRS version 6.0.22
 - Znuny4OTRS 6.0.50

### Additional information
https://github.com/znuny/Znuny4OTRS-Repo/blob/master/Kernel/Output/HTML/FilterElementPost/Znuny4OTRSRemoveBSAdvertisements.pm#L478

**Comment by rolfschmidt** [comment]
Hi @NeverMin,
thanks for your report! Hopefully we get this stuff now blocked more consistently.

**Release**
Znuny4OTRS-Repo 6.0.51

Best regards,
Rolf
