### ISSUE TITLE
Please support OTRS Fork OTOBO

### ISSUE THREAD

**Issue by torakaswp** [znuny/Znuny4OTRS-Repo#19]
Hi,

can you migrate the Znuny OTRS Repo and projects for the OTRS fork otobo.

I think it's not that much work. The OPM file must change in the XML tag OTRS_PACKAGE to OTOBO_PACKAGE. Adapt VERSION and FRAMEWORK from 6 ... to 10 ...

The XML config file which is coded as BASE64 must be adapted from the XML TAG OTRS_CONFIG in OTOBO_CONFIG.

Can you please support OTOBO. Thank you very much.

**Comment by hanneshal** [comment]
Hi @torakaswp 

unfortunately we dont have any plans to especially support OTOBO for our packages. Right now we simply dont have the resources to do so. 
But you might ask the OTOBO Team. They already use parts of the Repo-code in their fork, so maybe they can help you out.

Regards

Johannes
