### ISSUE TITLE
Znuny4OTRSInput - Owner find in Ticket Owner View

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-Repo#3]
In the Ticket Owner View is a special Owner handling, where the agent can chose between old owners and a list of all owners. Depending on which select field was used a radio button is set to the matching select field.

Znuny4OTRSInput should also set the matching radio button after setting a new Owner.

**Comment by dennykorsukewitz** [comment]
Which OTRS Version?

**Comment by dennykorsukewitz** [comment]
This problem exists only in OTRS4.
Since this version is no longer current, this issue will be closed.
