### ISSUE TITLE
Hide input fields

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-Repo#5]
Znuny4OTRSInput should be extended to show and hide fields via nice clean .Show('...') and .Hide('...') interfaces. Currently hiding fields is manually done in couple of extensions which makes bugfixing, developing and porting more difficult than needed.

**Comment by dennykorsukewitz** [comment]
Extended with last commit.
https://github.com/znuny/Znuny4OTRS-Repo/commit/5d91e5a531ed1555256ac647fd7e97158daec5b4
