### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-Repo#9]
Currently there is no README.md and description for this package. This file should be added.

**Comment by dennykorsukewitz** [comment]
Added README.md:

https://github.com/znuny/Znuny4OTRS-Repo/commit/dc63d12e284f721fcf68b0d8987336ddcd21269b#diff-04c6e90faac2675aa89e2176d2eec7d8

Updated:
https://github.com/znuny/Znuny4OTRS-Repo/commit/1227f70fa91ed2d06952dd9db9c335cdd5eb84b0

Fixed.
